# THIS YAML SETTING IS USED AS A BASE TO PRODUCE THE 'PREPROCESSING.YAML' ONE.
# THIS IT IS MEANT TO BE USED AS A STARTING POINT AND DOCUMENTATION ONE (see all the different choises a user has).

LOADER:
  src_data:
    - REMITTANCE
    # - FUNSD
    # - PAU
    # - CUSTOM
FEATURES:
  add_embs: true
  add_epolar: true
  add_edist: false
  add_eshared: false
  add_fudge: false
  add_geom: false
  add_size: false
  add_hist: false
  add_visual: false
GRAPHS:
  edge_type:
    - fully
    # - knn
  data_type:
    - img
    # - pdf
  node_granularity:
    - gt
    # - ocr
    # - yolo  
  